v {xschem version=3.4.4 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {Frequency Bandwidth} 685 -930 0 1 1 1 {}
N 1050 -460 1190 -460 {
lab=vout}
N 1170 -400 1310 -400 {
lab=VSUB}
N 1310 -400 1350 -400 {
lab=VSUB}
N 1190 -460 1480 -460 {
lab=vout}
N 230 -640 870 -640 {
lab=dvdd}
N 230 -640 230 -230 {
lab=dvdd}
N 910 -640 910 -520 {
lab=dvdd}
N 870 -640 910 -640 {
lab=dvdd}
N 870 -610 870 -530 {
lab=avdd}
N 310 -610 870 -610 {
lab=avdd}
N 300 -610 300 -230 {
lab=avdd}
N 820 -580 820 -550 {
lab=ibias}
N 420 -580 420 -230 {
lab=ibias}
N 630 -360 810 -360 {
lab=ena}
N 840 -350 840 -320 {
lab=vhyst_0}
N 710 -320 840 -320 {
lab=vhyst_0}
N 710 -320 710 -230 {
lab=vhyst_0}
N 860 -350 860 -270 {
lab=vhyst_1}
N 790 -270 860 -270 {
lab=vhyst_1}
N 870 -240 870 -230 {
lab=avss}
N 870 -240 890 -240 {
lab=avss}
N 890 -240 900 -240 {
lab=avss}
N 900 -390 900 -240 {
lab=avss}
N 940 -390 940 -240 {
lab=dvss}
N 940 -240 960 -240 {
lab=dvss}
N 960 -240 960 -230 {
lab=dvss}
N 230 -160 960 -160 {
lab=VSUB}
N 180 -160 230 -160 {
lab=VSUB}
N 510 -160 510 -120 {
lab=VSUB}
N 420 -580 820 -580 {
lab=ibias}
N 300 -610 310 -610 {
lab=avdd}
N 580 -550 580 -540 {
lab=vinp}
N 580 -480 580 -470 {
lab=inx}
N 490 -240 490 -230 {
lab=inx}
N 630 -360 630 -280 {
lab=ena}
N 630 -220 630 -180 {
lab=VSUB}
N 790 -270 790 -260 {
lab=vhyst_1}
N 790 -200 790 -170 {
lab=VSUB}
N 630 -170 630 -160 {
lab=VSUB}
N 230 -170 230 -160 {
lab=VSUB}
N 300 -170 300 -160 {
lab=VSUB}
N 420 -170 420 -160 {
lab=VSUB}
N 490 -170 490 -160 {
lab=VSUB}
N 630 -180 630 -170 {
lab=VSUB}
N 710 -170 710 -160 {
lab=VSUB}
N 790 -170 790 -160 {
lab=VSUB}
N 960 -170 960 -160 {
lab=VSUB}
N 870 -170 870 -160 {
lab=VSUB}
N 720 -550 720 -510 {
lab=vinp}
N 720 -510 750 -510 {
lab=vinp}
N 580 -470 580 -460 {
lab=inx}
N 720 -430 720 -400 {
lab=vinn}
N 720 -430 750 -430 {
lab=vinn}
N 720 -400 720 -390 {
lab=vinn}
N 490 -470 490 -240 {
lab=inx}
N 490 -470 580 -470 {
lab=inx}
N 580 -550 620 -550 {
lab=vinp}
N 680 -390 720 -390 {
lab=vinn}
N 580 -390 620 -390 {
lab=vinn}
N 580 -400 580 -390 {
lab=vinn}
N 620 -550 690 -550 {
lab=vinp}
N 690 -550 720 -550 {
lab=vinp}
N 620 -390 680 -390 {
lab=vinn}
C {devices/code_shown.sym} -720 -490 0 0 {name=CONTROL only_toplevel=false value=".control

ac dec 20 1 1e12
plot v(vout)
plot v(dvdd)
plot v(avdd)

meas ac peak MAX vmag(vout) FROM=2 TO=1.5GHz
let f3db = peak/sqrt(2)
meas ac f1 when vmag(vout)=f3db RISE=1
meas ac f2 when vmag(vout)=f3db FALL=1

let f3 = $&f2
echo $&f3 > \{simpath\}/\{filename\}_\{N\}.data

write ngspice/frequencyBandwidth.raw

.endc
"}
C {devices/code_shown.sym} -830 -810 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include \{DUT_path\}

.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/combined/sky130.lib.spice \{corner\}

.option TEMP=\{temperature\} 
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
.option savecurrents
.option save all
"}
C {devices/lab_pin.sym} 1480 -460 2 0 {name=p8 sig_type=std_logic lab=vout


}
C {devices/vsource.sym} 300 -200 0 0 {name=Vavdd value="DC \{Vavdd\}" savecurrent=false}
C {devices/res.sym} 1170 -430 0 0 {name=Rout
value=\{Rout\}
device=resistor}
C {devices/capa.sym} 1310 -430 0 0 {name=Cout
value=\{Cout\}}
C {devices/lab_pin.sym} 1350 -400 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 230 -200 0 0 {name=Vdvdd value="DC \{Vdvdd\}" savecurrent=false}
C {devices/vsource.sym} 630 -250 0 0 {name=Vena value="DC [\{ena\} * \{Vdvdd\}]" savecurrent=false}
C {devices/vsource.sym} 710 -200 0 0 {name=Vhyst0 value="DC [\{Vhyst_0\}* \{Vdvdd\}]" savecurrent=false}
C {devices/vsource.sym} 790 -230 0 0 {name=Vhyst1 value="DC [\{Vhyst_1\}* \{Vdvdd\}]" savecurrent=false}
C {devices/vsource.sym} 870 -200 0 0 {name=Vavss value="DC \{Vavss\}" savecurrent=false}
C {devices/vsource.sym} 960 -200 0 0 {name=Vdvss value="DC \{Vdvss\}" savecurrent=false}
C {devices/lab_pin.sym} 180 -160 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/res.sym} 510 -90 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 510 -60 0 0 {name=l1 lab=GND}
C {devices/isource.sym} 420 -200 2 0 {name=Iibias value="DC \{ibias\}"}
C {devices/lab_pin.sym} 230 -480 0 0 {name=p2 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} 300 -480 0 0 {name=p3 sig_type=std_logic lab=avdd}
C {devices/lab_pin.sym} 420 -480 0 0 {name=p4 sig_type=std_logic lab=ibias}
C {devices/lab_pin.sym} 630 -340 0 0 {name=p7 sig_type=std_logic lab=ena}
C {devices/lab_pin.sym} 900 -250 0 0 {name=p11 sig_type=std_logic lab=avss}
C {devices/lab_pin.sym} 940 -280 0 1 {name=p12 sig_type=std_logic lab=dvss}
C {devices/lab_pin.sym} 720 -510 0 0 {name=p5 sig_type=std_logic lab=vinp}
C {devices/lab_pin.sym} 720 -430 0 0 {name=p6 sig_type=std_logic lab=vinn}
C {Chipalooza_April2024_Comparator.sym} 900 -460 0 0 {name=XDUT}
C {devices/lab_pin.sym} 490 -470 0 0 {name=p13 sig_type=std_logic lab=inx}
C {devices/vsource.sym} 580 -510 0 0 {name=VVpos value="DC 1.65 AC 1.65" savecurrent=false}
C {devices/vsource.sym} 580 -430 0 0 {name=VVneg value="DC -1.65" savecurrent=false}
C {devices/vsource.sym} 490 -200 0 0 {name=VVcm value="DC \{Vcm\}" savecurrent=false}
C {devices/lab_pin.sym} 710 -320 0 0 {name=p9 sig_type=std_logic lab=vhyst_0}
C {devices/lab_pin.sym} 790 -270 0 0 {name=p10 sig_type=std_logic lab=vhyst_1}
