v {xschem version=3.4.4 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {Power Consumption} 435 -770 0 0 1 1 {}
N 1120 -360 1260 -360 {
lab=vout}
N 1240 -300 1380 -300 {
lab=VSUB}
N 1380 -300 1420 -300 {
lab=VSUB}
N 1260 -360 1550 -360 {
lab=vout}
N 300 -540 940 -540 {
lab=dvdd}
N 300 -540 300 -130 {
lab=dvdd}
N 980 -540 980 -420 {
lab=dvdd}
N 940 -540 980 -540 {
lab=dvdd}
N 940 -510 940 -430 {
lab=avdd}
N 380 -510 940 -510 {
lab=avdd}
N 370 -510 370 -130 {
lab=avdd}
N 890 -480 890 -450 {
lab=ibias}
N 490 -480 490 -130 {
lab=ibias}
N 620 -330 820 -330 {
lab=vinn}
N 700 -260 880 -260 {
lab=ena}
N 910 -250 910 -220 {
lab=hyst0}
N 780 -220 910 -220 {
lab=hyst0}
N 780 -220 780 -130 {
lab=hyst0}
N 930 -250 930 -170 {
lab=hyst1}
N 860 -170 930 -170 {
lab=hyst1}
N 940 -140 940 -130 {
lab=avss}
N 940 -140 960 -140 {
lab=avss}
N 960 -140 970 -140 {
lab=avss}
N 970 -290 970 -140 {
lab=avss}
N 1010 -290 1010 -140 {
lab=dvss}
N 1010 -140 1030 -140 {
lab=dvss}
N 1030 -140 1030 -130 {
lab=dvss}
N 300 -60 1030 -60 {
lab=VSUB}
N 250 -60 300 -60 {
lab=VSUB}
N 580 -60 580 -20 {
lab=VSUB}
N 490 -480 890 -480 {
lab=ibias}
N 370 -510 380 -510 {
lab=avdd}
N 620 -410 820 -410 {
lab=vinp}
N 620 -410 620 -400 {
lab=vinp}
N 620 -340 620 -330 {
lab=vinn}
N 620 -330 620 -140 {
lab=vinn}
N 620 -140 620 -130 {
lab=vinn}
N 700 -260 700 -180 {
lab=ena}
N 700 -120 700 -80 {
lab=VSUB}
N 860 -170 860 -160 {
lab=hyst1}
N 860 -100 860 -70 {
lab=VSUB}
N 700 -70 700 -60 {
lab=VSUB}
N 300 -70 300 -60 {
lab=VSUB}
N 370 -70 370 -60 {
lab=VSUB}
N 490 -70 490 -60 {
lab=VSUB}
N 620 -70 620 -60 {
lab=VSUB}
N 700 -80 700 -70 {
lab=VSUB}
N 780 -70 780 -60 {
lab=VSUB}
N 860 -70 860 -60 {
lab=VSUB}
N 1030 -70 1030 -60 {
lab=VSUB}
N 940 -70 940 -60 {
lab=VSUB}
C {devices/lab_pin.sym} 1550 -360 2 0 {name=p8 sig_type=std_logic lab=vout


}
C {devices/vsource.sym} 370 -100 0 0 {name=Vavdd value="DC \{Vavdd\}" savecurrent=false}
C {devices/res.sym} 1240 -330 0 0 {name=Rout
value=\{Rout\}
device=resistor}
C {devices/capa.sym} 1380 -330 0 0 {name=Cout
value=\{Cout\}}
C {devices/lab_pin.sym} 1420 -300 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 300 -100 0 0 {name=Vdvdd value="DC \{Vdvdd\}" savecurrent=false}
C {devices/vsource.sym} 620 -100 0 0 {name=Vvcm value="DC \{Vvcm\}" savecurrent=false}
C {devices/vsource.sym} 700 -150 0 0 {name=Vena value="DC \{ena\}" savecurrent=false}
C {devices/vsource.sym} 780 -100 0 0 {name=Vhyst0 value="DC 1.8" savecurrent=false}
C {devices/vsource.sym} 940 -100 0 0 {name=Vavss value="DC \{Vavss\}" savecurrent=false}
C {devices/vsource.sym} 1030 -100 0 0 {name=Vdvss value="DC \{Vdvss\}" savecurrent=false}
C {devices/lab_pin.sym} 250 -60 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/res.sym} 580 10 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 580 40 0 0 {name=l1 lab=GND}
C {devices/isource.sym} 490 -100 2 0 {name=Iibias value="DC \{ibias\}"}
C {devices/lab_pin.sym} 300 -380 0 0 {name=p2 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} 370 -380 0 0 {name=p3 sig_type=std_logic lab=avdd}
C {devices/lab_pin.sym} 490 -380 0 0 {name=p4 sig_type=std_logic lab=ibias}
C {devices/lab_pin.sym} 700 -240 0 0 {name=p7 sig_type=std_logic lab=ena}
C {devices/lab_pin.sym} 780 -200 0 0 {name=p9 sig_type=std_logic lab=hyst0}
C {devices/lab_pin.sym} 970 -150 0 0 {name=p11 sig_type=std_logic lab=avss}
C {devices/lab_pin.sym} 1010 -180 0 1 {name=p12 sig_type=std_logic lab=dvss}
C {devices/vsource.sym} 620 -370 0 0 {name=VVdiff value="DC \{Vdiff\}" savecurrent=false}
C {devices/lab_pin.sym} 620 -410 0 0 {name=p5 sig_type=std_logic lab=vinp}
C {devices/lab_pin.sym} 620 -330 0 0 {name=p6 sig_type=std_logic lab=vinn}
C {devices/code_shown.sym} -790 -390 0 0 {name=CONTROL only_toplevel=false value=".control 
op

set wr_singlescale
wrdata \{simpath\}/\{filename\}_\{N\}.data -I(Vdvdd)
write ngspice/powerConsumption.raw

quit

.endc
"}
C {devices/code_shown.sym} -580 -670 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include \{DUT_path\}

.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/combined/sky130.lib.spice \{corner\}

.option TEMP=\{temperature\} 
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
.option savecurrents
.option save all
"}
C {Chipalooza_April2024_Comparator.sym} 970 -360 0 0 {name=XDUT}
C {devices/lab_pin.sym} 860 -170 0 0 {name=p10 sig_type=std_logic lab=hyst1}
C {devices/vsource.sym} 860 -130 0 0 {name=Vhyst1 value="DC 1.8" savecurrent=false}
